### ISSUE TITLE
Add authentication for http client pipeline

### ISSUE THREAD

**Issue by simonvpe** [simonvpe/trawler#4]
Example:
```yaml
pipelines:
  - name: my-client
    pipeline: http-client
    source: ...
    auth: { bearer: Basic, token: "user:password", base64encode: true }
```
