### ISSUE TITLE
Add magic variables to pipeline configurations

### ISSUE THREAD

**Issue by simonvpe** [simonvpe/trawler#5]
When configuring a pipeline in the yaml file, it would be nice to be able to reference arbitrary json fields from the input event in the configuration fields. Probably the best solution would be to use inja for this, and somehow specify in the `trawler::config` for each field whether it is supported, since some fields obviously are evaluated at spawn-time.

Example:
```yaml
pipelines:
  - name: my-pipeline
    pipeline: some-pipeline
    data: The input field "hello" was {{ hello }}
```
